### ISSUE TITLE
sequence error

### ISSUE THREAD

**Issue by kavurianil** [cybertec-postgresql/ora_migrator#9] opened 2018-08-11 01:33 UTC
NOTICE:  Creating Oracle metadata views in schema "ora_stage" ...
NOTICE:  Copy definitions to PostgreSQL staging schema "pgsql_stage" ...
ERROR:  ON CONFLICT DO UPDATE command cannot affect row a second time
HINT:  Ensure that no rows proposed for insertion within the same command have duplicate constrained values.
CONTEXT:  SQL statement "INSERT INTO sequences (schema, sequence_name, min_value, max_value, increment_by,
                       cyclical, cache_size, last_value, oracle_value)
   SELECT oracle_tolower(schema),
          oracle_tolower(sequence_name),
          adjust_to_bigint(min_value),
          adjust_to_bigint(max_value),
          adjust_to_bigint(increment_by),
          cyclical,
          GREATEST(cache_size, 1) AS cache_size,
          adjust_to_bigint(last_value),
          adjust_to_bigint(last_value)
   FROM ora_stage.sequences
   WHERE $1 IS NULL OR schema =ANY ($1)
ON CONFLICT ON CONSTRAINT sequences_pkey DO UPDATE SET
   min_value    = EXCLUDED.min_value,
   max_value    = EXCLUDED.max_value,
   increment_by = EXCLUDED.increment_by,
   cyclical     = EXCLUDED.cyclical,
   cache_size   = EXCLUDED.cache_size,
   oracle_value = EXCLUDED.oracle_value"
PL/pgSQL function public.oracle_migrate_refresh(name,name,name,name[],integer) line 245 at EXECUTE
PL/pgSQL function public.oracle_migrate_prepare(name,name,name,name[],integer) line 245 at RETURN

**Comment by laurenz** [comment] 2018-08-13 08:25
This is a duplicate of #8.

Could you get the current development version (from Git or [here](https://github.com/cybertec-postgresql/ora_migrator/archive/master.zip)) that contains patch a79d8d516a6b37aad38970b26d2911d055e41003 and see if that solves your problem?

**Comment by laurenz** [comment] 2018-09-03 09:04
I'll close the issue since I believe that this fixes the problem.

Don't hesitate to reopen it if I am wrong.

**Closed by laurenz** 2018-09-03 09:04 UTC
Labels: bug, duplicate
